// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: loadbalancer.proto

#include "loadbalancer.pb.h"
#include "loadbalancer.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace loadbalancer {

static const char* LoadBalancer_method_names[] = {
  "/loadbalancer.LoadBalancer/ReserveLoadBalancer",
  "/loadbalancer.LoadBalancer/GetLoadBalancer",
  "/loadbalancer.LoadBalancer/LoadBalancerStatus",
  "/loadbalancer.LoadBalancer/FreeLoadBalancer",
  "/loadbalancer.LoadBalancer/AddSenders",
  "/loadbalancer.LoadBalancer/RemoveSenders",
  "/loadbalancer.LoadBalancer/Register",
  "/loadbalancer.LoadBalancer/SetSlotDemands",
  "/loadbalancer.LoadBalancer/Deregister",
  "/loadbalancer.LoadBalancer/SendState",
  "/loadbalancer.LoadBalancer/Overview",
  "/loadbalancer.LoadBalancer/Timeseries",
  "/loadbalancer.LoadBalancer/Version",
  "/loadbalancer.LoadBalancer/CreateToken",
  "/loadbalancer.LoadBalancer/ListTokenPermissions",
  "/loadbalancer.LoadBalancer/ListChildTokens",
  "/loadbalancer.LoadBalancer/RevokeToken",
};

std::unique_ptr< LoadBalancer::Stub> LoadBalancer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< LoadBalancer::Stub> stub(new LoadBalancer::Stub(channel, options));
  return stub;
}

LoadBalancer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ReserveLoadBalancer_(LoadBalancer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetLoadBalancer_(LoadBalancer_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_LoadBalancerStatus_(LoadBalancer_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_FreeLoadBalancer_(LoadBalancer_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AddSenders_(LoadBalancer_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RemoveSenders_(LoadBalancer_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Register_(LoadBalancer_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetSlotDemands_(LoadBalancer_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Deregister_(LoadBalancer_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendState_(LoadBalancer_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Overview_(LoadBalancer_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Timeseries_(LoadBalancer_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Version_(LoadBalancer_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateToken_(LoadBalancer_method_names[13], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListTokenPermissions_(LoadBalancer_method_names[14], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListChildTokens_(LoadBalancer_method_names[15], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RevokeToken_(LoadBalancer_method_names[16], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status LoadBalancer::Stub::ReserveLoadBalancer(::grpc::ClientContext* context, const ::loadbalancer::ReserveLoadBalancerRequest& request, ::loadbalancer::ReserveLoadBalancerReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::loadbalancer::ReserveLoadBalancerRequest, ::loadbalancer::ReserveLoadBalancerReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReserveLoadBalancer_, context, request, response);
}

void LoadBalancer::Stub::async::ReserveLoadBalancer(::grpc::ClientContext* context, const ::loadbalancer::ReserveLoadBalancerRequest* request, ::loadbalancer::ReserveLoadBalancerReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::loadbalancer::ReserveLoadBalancerRequest, ::loadbalancer::ReserveLoadBalancerReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReserveLoadBalancer_, context, request, response, std::move(f));
}

void LoadBalancer::Stub::async::ReserveLoadBalancer(::grpc::ClientContext* context, const ::loadbalancer::ReserveLoadBalancerRequest* request, ::loadbalancer::ReserveLoadBalancerReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReserveLoadBalancer_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::ReserveLoadBalancerReply>* LoadBalancer::Stub::PrepareAsyncReserveLoadBalancerRaw(::grpc::ClientContext* context, const ::loadbalancer::ReserveLoadBalancerRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::loadbalancer::ReserveLoadBalancerReply, ::loadbalancer::ReserveLoadBalancerRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReserveLoadBalancer_, context, request);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::ReserveLoadBalancerReply>* LoadBalancer::Stub::AsyncReserveLoadBalancerRaw(::grpc::ClientContext* context, const ::loadbalancer::ReserveLoadBalancerRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReserveLoadBalancerRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LoadBalancer::Stub::GetLoadBalancer(::grpc::ClientContext* context, const ::loadbalancer::GetLoadBalancerRequest& request, ::loadbalancer::ReserveLoadBalancerReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::loadbalancer::GetLoadBalancerRequest, ::loadbalancer::ReserveLoadBalancerReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetLoadBalancer_, context, request, response);
}

void LoadBalancer::Stub::async::GetLoadBalancer(::grpc::ClientContext* context, const ::loadbalancer::GetLoadBalancerRequest* request, ::loadbalancer::ReserveLoadBalancerReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::loadbalancer::GetLoadBalancerRequest, ::loadbalancer::ReserveLoadBalancerReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetLoadBalancer_, context, request, response, std::move(f));
}

void LoadBalancer::Stub::async::GetLoadBalancer(::grpc::ClientContext* context, const ::loadbalancer::GetLoadBalancerRequest* request, ::loadbalancer::ReserveLoadBalancerReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetLoadBalancer_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::ReserveLoadBalancerReply>* LoadBalancer::Stub::PrepareAsyncGetLoadBalancerRaw(::grpc::ClientContext* context, const ::loadbalancer::GetLoadBalancerRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::loadbalancer::ReserveLoadBalancerReply, ::loadbalancer::GetLoadBalancerRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetLoadBalancer_, context, request);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::ReserveLoadBalancerReply>* LoadBalancer::Stub::AsyncGetLoadBalancerRaw(::grpc::ClientContext* context, const ::loadbalancer::GetLoadBalancerRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetLoadBalancerRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LoadBalancer::Stub::LoadBalancerStatus(::grpc::ClientContext* context, const ::loadbalancer::LoadBalancerStatusRequest& request, ::loadbalancer::LoadBalancerStatusReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::loadbalancer::LoadBalancerStatusRequest, ::loadbalancer::LoadBalancerStatusReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_LoadBalancerStatus_, context, request, response);
}

void LoadBalancer::Stub::async::LoadBalancerStatus(::grpc::ClientContext* context, const ::loadbalancer::LoadBalancerStatusRequest* request, ::loadbalancer::LoadBalancerStatusReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::loadbalancer::LoadBalancerStatusRequest, ::loadbalancer::LoadBalancerStatusReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LoadBalancerStatus_, context, request, response, std::move(f));
}

void LoadBalancer::Stub::async::LoadBalancerStatus(::grpc::ClientContext* context, const ::loadbalancer::LoadBalancerStatusRequest* request, ::loadbalancer::LoadBalancerStatusReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LoadBalancerStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::LoadBalancerStatusReply>* LoadBalancer::Stub::PrepareAsyncLoadBalancerStatusRaw(::grpc::ClientContext* context, const ::loadbalancer::LoadBalancerStatusRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::loadbalancer::LoadBalancerStatusReply, ::loadbalancer::LoadBalancerStatusRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_LoadBalancerStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::LoadBalancerStatusReply>* LoadBalancer::Stub::AsyncLoadBalancerStatusRaw(::grpc::ClientContext* context, const ::loadbalancer::LoadBalancerStatusRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLoadBalancerStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LoadBalancer::Stub::FreeLoadBalancer(::grpc::ClientContext* context, const ::loadbalancer::FreeLoadBalancerRequest& request, ::loadbalancer::FreeLoadBalancerReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::loadbalancer::FreeLoadBalancerRequest, ::loadbalancer::FreeLoadBalancerReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_FreeLoadBalancer_, context, request, response);
}

void LoadBalancer::Stub::async::FreeLoadBalancer(::grpc::ClientContext* context, const ::loadbalancer::FreeLoadBalancerRequest* request, ::loadbalancer::FreeLoadBalancerReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::loadbalancer::FreeLoadBalancerRequest, ::loadbalancer::FreeLoadBalancerReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FreeLoadBalancer_, context, request, response, std::move(f));
}

void LoadBalancer::Stub::async::FreeLoadBalancer(::grpc::ClientContext* context, const ::loadbalancer::FreeLoadBalancerRequest* request, ::loadbalancer::FreeLoadBalancerReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FreeLoadBalancer_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::FreeLoadBalancerReply>* LoadBalancer::Stub::PrepareAsyncFreeLoadBalancerRaw(::grpc::ClientContext* context, const ::loadbalancer::FreeLoadBalancerRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::loadbalancer::FreeLoadBalancerReply, ::loadbalancer::FreeLoadBalancerRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_FreeLoadBalancer_, context, request);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::FreeLoadBalancerReply>* LoadBalancer::Stub::AsyncFreeLoadBalancerRaw(::grpc::ClientContext* context, const ::loadbalancer::FreeLoadBalancerRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFreeLoadBalancerRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LoadBalancer::Stub::AddSenders(::grpc::ClientContext* context, const ::loadbalancer::AddSendersRequest& request, ::loadbalancer::AddSendersReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::loadbalancer::AddSendersRequest, ::loadbalancer::AddSendersReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AddSenders_, context, request, response);
}

void LoadBalancer::Stub::async::AddSenders(::grpc::ClientContext* context, const ::loadbalancer::AddSendersRequest* request, ::loadbalancer::AddSendersReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::loadbalancer::AddSendersRequest, ::loadbalancer::AddSendersReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddSenders_, context, request, response, std::move(f));
}

void LoadBalancer::Stub::async::AddSenders(::grpc::ClientContext* context, const ::loadbalancer::AddSendersRequest* request, ::loadbalancer::AddSendersReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddSenders_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::AddSendersReply>* LoadBalancer::Stub::PrepareAsyncAddSendersRaw(::grpc::ClientContext* context, const ::loadbalancer::AddSendersRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::loadbalancer::AddSendersReply, ::loadbalancer::AddSendersRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AddSenders_, context, request);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::AddSendersReply>* LoadBalancer::Stub::AsyncAddSendersRaw(::grpc::ClientContext* context, const ::loadbalancer::AddSendersRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAddSendersRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LoadBalancer::Stub::RemoveSenders(::grpc::ClientContext* context, const ::loadbalancer::RemoveSendersRequest& request, ::loadbalancer::RemoveSendersReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::loadbalancer::RemoveSendersRequest, ::loadbalancer::RemoveSendersReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RemoveSenders_, context, request, response);
}

void LoadBalancer::Stub::async::RemoveSenders(::grpc::ClientContext* context, const ::loadbalancer::RemoveSendersRequest* request, ::loadbalancer::RemoveSendersReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::loadbalancer::RemoveSendersRequest, ::loadbalancer::RemoveSendersReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RemoveSenders_, context, request, response, std::move(f));
}

void LoadBalancer::Stub::async::RemoveSenders(::grpc::ClientContext* context, const ::loadbalancer::RemoveSendersRequest* request, ::loadbalancer::RemoveSendersReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RemoveSenders_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::RemoveSendersReply>* LoadBalancer::Stub::PrepareAsyncRemoveSendersRaw(::grpc::ClientContext* context, const ::loadbalancer::RemoveSendersRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::loadbalancer::RemoveSendersReply, ::loadbalancer::RemoveSendersRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RemoveSenders_, context, request);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::RemoveSendersReply>* LoadBalancer::Stub::AsyncRemoveSendersRaw(::grpc::ClientContext* context, const ::loadbalancer::RemoveSendersRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRemoveSendersRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LoadBalancer::Stub::Register(::grpc::ClientContext* context, const ::loadbalancer::RegisterRequest& request, ::loadbalancer::RegisterReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::loadbalancer::RegisterRequest, ::loadbalancer::RegisterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Register_, context, request, response);
}

void LoadBalancer::Stub::async::Register(::grpc::ClientContext* context, const ::loadbalancer::RegisterRequest* request, ::loadbalancer::RegisterReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::loadbalancer::RegisterRequest, ::loadbalancer::RegisterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Register_, context, request, response, std::move(f));
}

void LoadBalancer::Stub::async::Register(::grpc::ClientContext* context, const ::loadbalancer::RegisterRequest* request, ::loadbalancer::RegisterReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Register_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::RegisterReply>* LoadBalancer::Stub::PrepareAsyncRegisterRaw(::grpc::ClientContext* context, const ::loadbalancer::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::loadbalancer::RegisterReply, ::loadbalancer::RegisterRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Register_, context, request);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::RegisterReply>* LoadBalancer::Stub::AsyncRegisterRaw(::grpc::ClientContext* context, const ::loadbalancer::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegisterRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LoadBalancer::Stub::SetSlotDemands(::grpc::ClientContext* context, const ::loadbalancer::SetSlotDemandsRequest& request, ::loadbalancer::SetSlotDemandsReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::loadbalancer::SetSlotDemandsRequest, ::loadbalancer::SetSlotDemandsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetSlotDemands_, context, request, response);
}

void LoadBalancer::Stub::async::SetSlotDemands(::grpc::ClientContext* context, const ::loadbalancer::SetSlotDemandsRequest* request, ::loadbalancer::SetSlotDemandsReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::loadbalancer::SetSlotDemandsRequest, ::loadbalancer::SetSlotDemandsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetSlotDemands_, context, request, response, std::move(f));
}

void LoadBalancer::Stub::async::SetSlotDemands(::grpc::ClientContext* context, const ::loadbalancer::SetSlotDemandsRequest* request, ::loadbalancer::SetSlotDemandsReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetSlotDemands_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::SetSlotDemandsReply>* LoadBalancer::Stub::PrepareAsyncSetSlotDemandsRaw(::grpc::ClientContext* context, const ::loadbalancer::SetSlotDemandsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::loadbalancer::SetSlotDemandsReply, ::loadbalancer::SetSlotDemandsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetSlotDemands_, context, request);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::SetSlotDemandsReply>* LoadBalancer::Stub::AsyncSetSlotDemandsRaw(::grpc::ClientContext* context, const ::loadbalancer::SetSlotDemandsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetSlotDemandsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LoadBalancer::Stub::Deregister(::grpc::ClientContext* context, const ::loadbalancer::DeregisterRequest& request, ::loadbalancer::DeregisterReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::loadbalancer::DeregisterRequest, ::loadbalancer::DeregisterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Deregister_, context, request, response);
}

void LoadBalancer::Stub::async::Deregister(::grpc::ClientContext* context, const ::loadbalancer::DeregisterRequest* request, ::loadbalancer::DeregisterReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::loadbalancer::DeregisterRequest, ::loadbalancer::DeregisterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Deregister_, context, request, response, std::move(f));
}

void LoadBalancer::Stub::async::Deregister(::grpc::ClientContext* context, const ::loadbalancer::DeregisterRequest* request, ::loadbalancer::DeregisterReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Deregister_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::DeregisterReply>* LoadBalancer::Stub::PrepareAsyncDeregisterRaw(::grpc::ClientContext* context, const ::loadbalancer::DeregisterRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::loadbalancer::DeregisterReply, ::loadbalancer::DeregisterRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Deregister_, context, request);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::DeregisterReply>* LoadBalancer::Stub::AsyncDeregisterRaw(::grpc::ClientContext* context, const ::loadbalancer::DeregisterRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeregisterRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LoadBalancer::Stub::SendState(::grpc::ClientContext* context, const ::loadbalancer::SendStateRequest& request, ::loadbalancer::SendStateReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::loadbalancer::SendStateRequest, ::loadbalancer::SendStateReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendState_, context, request, response);
}

void LoadBalancer::Stub::async::SendState(::grpc::ClientContext* context, const ::loadbalancer::SendStateRequest* request, ::loadbalancer::SendStateReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::loadbalancer::SendStateRequest, ::loadbalancer::SendStateReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendState_, context, request, response, std::move(f));
}

void LoadBalancer::Stub::async::SendState(::grpc::ClientContext* context, const ::loadbalancer::SendStateRequest* request, ::loadbalancer::SendStateReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendState_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::SendStateReply>* LoadBalancer::Stub::PrepareAsyncSendStateRaw(::grpc::ClientContext* context, const ::loadbalancer::SendStateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::loadbalancer::SendStateReply, ::loadbalancer::SendStateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendState_, context, request);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::SendStateReply>* LoadBalancer::Stub::AsyncSendStateRaw(::grpc::ClientContext* context, const ::loadbalancer::SendStateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendStateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LoadBalancer::Stub::Overview(::grpc::ClientContext* context, const ::loadbalancer::OverviewRequest& request, ::loadbalancer::OverviewReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::loadbalancer::OverviewRequest, ::loadbalancer::OverviewReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Overview_, context, request, response);
}

void LoadBalancer::Stub::async::Overview(::grpc::ClientContext* context, const ::loadbalancer::OverviewRequest* request, ::loadbalancer::OverviewReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::loadbalancer::OverviewRequest, ::loadbalancer::OverviewReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Overview_, context, request, response, std::move(f));
}

void LoadBalancer::Stub::async::Overview(::grpc::ClientContext* context, const ::loadbalancer::OverviewRequest* request, ::loadbalancer::OverviewReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Overview_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::OverviewReply>* LoadBalancer::Stub::PrepareAsyncOverviewRaw(::grpc::ClientContext* context, const ::loadbalancer::OverviewRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::loadbalancer::OverviewReply, ::loadbalancer::OverviewRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Overview_, context, request);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::OverviewReply>* LoadBalancer::Stub::AsyncOverviewRaw(::grpc::ClientContext* context, const ::loadbalancer::OverviewRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncOverviewRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LoadBalancer::Stub::Timeseries(::grpc::ClientContext* context, const ::loadbalancer::TimeseriesRequest& request, ::loadbalancer::TimeseriesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::loadbalancer::TimeseriesRequest, ::loadbalancer::TimeseriesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Timeseries_, context, request, response);
}

void LoadBalancer::Stub::async::Timeseries(::grpc::ClientContext* context, const ::loadbalancer::TimeseriesRequest* request, ::loadbalancer::TimeseriesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::loadbalancer::TimeseriesRequest, ::loadbalancer::TimeseriesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Timeseries_, context, request, response, std::move(f));
}

void LoadBalancer::Stub::async::Timeseries(::grpc::ClientContext* context, const ::loadbalancer::TimeseriesRequest* request, ::loadbalancer::TimeseriesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Timeseries_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::TimeseriesResponse>* LoadBalancer::Stub::PrepareAsyncTimeseriesRaw(::grpc::ClientContext* context, const ::loadbalancer::TimeseriesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::loadbalancer::TimeseriesResponse, ::loadbalancer::TimeseriesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Timeseries_, context, request);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::TimeseriesResponse>* LoadBalancer::Stub::AsyncTimeseriesRaw(::grpc::ClientContext* context, const ::loadbalancer::TimeseriesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncTimeseriesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LoadBalancer::Stub::Version(::grpc::ClientContext* context, const ::loadbalancer::VersionRequest& request, ::loadbalancer::VersionReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::loadbalancer::VersionRequest, ::loadbalancer::VersionReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Version_, context, request, response);
}

void LoadBalancer::Stub::async::Version(::grpc::ClientContext* context, const ::loadbalancer::VersionRequest* request, ::loadbalancer::VersionReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::loadbalancer::VersionRequest, ::loadbalancer::VersionReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Version_, context, request, response, std::move(f));
}

void LoadBalancer::Stub::async::Version(::grpc::ClientContext* context, const ::loadbalancer::VersionRequest* request, ::loadbalancer::VersionReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Version_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::VersionReply>* LoadBalancer::Stub::PrepareAsyncVersionRaw(::grpc::ClientContext* context, const ::loadbalancer::VersionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::loadbalancer::VersionReply, ::loadbalancer::VersionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Version_, context, request);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::VersionReply>* LoadBalancer::Stub::AsyncVersionRaw(::grpc::ClientContext* context, const ::loadbalancer::VersionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncVersionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LoadBalancer::Stub::CreateToken(::grpc::ClientContext* context, const ::loadbalancer::CreateTokenRequest& request, ::loadbalancer::CreateTokenReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::loadbalancer::CreateTokenRequest, ::loadbalancer::CreateTokenReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateToken_, context, request, response);
}

void LoadBalancer::Stub::async::CreateToken(::grpc::ClientContext* context, const ::loadbalancer::CreateTokenRequest* request, ::loadbalancer::CreateTokenReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::loadbalancer::CreateTokenRequest, ::loadbalancer::CreateTokenReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateToken_, context, request, response, std::move(f));
}

void LoadBalancer::Stub::async::CreateToken(::grpc::ClientContext* context, const ::loadbalancer::CreateTokenRequest* request, ::loadbalancer::CreateTokenReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateToken_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::CreateTokenReply>* LoadBalancer::Stub::PrepareAsyncCreateTokenRaw(::grpc::ClientContext* context, const ::loadbalancer::CreateTokenRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::loadbalancer::CreateTokenReply, ::loadbalancer::CreateTokenRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateToken_, context, request);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::CreateTokenReply>* LoadBalancer::Stub::AsyncCreateTokenRaw(::grpc::ClientContext* context, const ::loadbalancer::CreateTokenRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateTokenRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LoadBalancer::Stub::ListTokenPermissions(::grpc::ClientContext* context, const ::loadbalancer::ListTokenPermissionsRequest& request, ::loadbalancer::ListTokenPermissionsReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::loadbalancer::ListTokenPermissionsRequest, ::loadbalancer::ListTokenPermissionsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListTokenPermissions_, context, request, response);
}

void LoadBalancer::Stub::async::ListTokenPermissions(::grpc::ClientContext* context, const ::loadbalancer::ListTokenPermissionsRequest* request, ::loadbalancer::ListTokenPermissionsReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::loadbalancer::ListTokenPermissionsRequest, ::loadbalancer::ListTokenPermissionsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListTokenPermissions_, context, request, response, std::move(f));
}

void LoadBalancer::Stub::async::ListTokenPermissions(::grpc::ClientContext* context, const ::loadbalancer::ListTokenPermissionsRequest* request, ::loadbalancer::ListTokenPermissionsReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListTokenPermissions_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::ListTokenPermissionsReply>* LoadBalancer::Stub::PrepareAsyncListTokenPermissionsRaw(::grpc::ClientContext* context, const ::loadbalancer::ListTokenPermissionsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::loadbalancer::ListTokenPermissionsReply, ::loadbalancer::ListTokenPermissionsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListTokenPermissions_, context, request);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::ListTokenPermissionsReply>* LoadBalancer::Stub::AsyncListTokenPermissionsRaw(::grpc::ClientContext* context, const ::loadbalancer::ListTokenPermissionsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListTokenPermissionsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LoadBalancer::Stub::ListChildTokens(::grpc::ClientContext* context, const ::loadbalancer::ListChildTokensRequest& request, ::loadbalancer::ListChildTokensReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::loadbalancer::ListChildTokensRequest, ::loadbalancer::ListChildTokensReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListChildTokens_, context, request, response);
}

void LoadBalancer::Stub::async::ListChildTokens(::grpc::ClientContext* context, const ::loadbalancer::ListChildTokensRequest* request, ::loadbalancer::ListChildTokensReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::loadbalancer::ListChildTokensRequest, ::loadbalancer::ListChildTokensReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListChildTokens_, context, request, response, std::move(f));
}

void LoadBalancer::Stub::async::ListChildTokens(::grpc::ClientContext* context, const ::loadbalancer::ListChildTokensRequest* request, ::loadbalancer::ListChildTokensReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListChildTokens_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::ListChildTokensReply>* LoadBalancer::Stub::PrepareAsyncListChildTokensRaw(::grpc::ClientContext* context, const ::loadbalancer::ListChildTokensRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::loadbalancer::ListChildTokensReply, ::loadbalancer::ListChildTokensRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListChildTokens_, context, request);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::ListChildTokensReply>* LoadBalancer::Stub::AsyncListChildTokensRaw(::grpc::ClientContext* context, const ::loadbalancer::ListChildTokensRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListChildTokensRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LoadBalancer::Stub::RevokeToken(::grpc::ClientContext* context, const ::loadbalancer::RevokeTokenRequest& request, ::loadbalancer::RevokeTokenReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::loadbalancer::RevokeTokenRequest, ::loadbalancer::RevokeTokenReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RevokeToken_, context, request, response);
}

void LoadBalancer::Stub::async::RevokeToken(::grpc::ClientContext* context, const ::loadbalancer::RevokeTokenRequest* request, ::loadbalancer::RevokeTokenReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::loadbalancer::RevokeTokenRequest, ::loadbalancer::RevokeTokenReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RevokeToken_, context, request, response, std::move(f));
}

void LoadBalancer::Stub::async::RevokeToken(::grpc::ClientContext* context, const ::loadbalancer::RevokeTokenRequest* request, ::loadbalancer::RevokeTokenReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RevokeToken_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::RevokeTokenReply>* LoadBalancer::Stub::PrepareAsyncRevokeTokenRaw(::grpc::ClientContext* context, const ::loadbalancer::RevokeTokenRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::loadbalancer::RevokeTokenReply, ::loadbalancer::RevokeTokenRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RevokeToken_, context, request);
}

::grpc::ClientAsyncResponseReader< ::loadbalancer::RevokeTokenReply>* LoadBalancer::Stub::AsyncRevokeTokenRaw(::grpc::ClientContext* context, const ::loadbalancer::RevokeTokenRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRevokeTokenRaw(context, request, cq);
  result->StartCall();
  return result;
}

LoadBalancer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LoadBalancer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LoadBalancer::Service, ::loadbalancer::ReserveLoadBalancerRequest, ::loadbalancer::ReserveLoadBalancerReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LoadBalancer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::loadbalancer::ReserveLoadBalancerRequest* req,
             ::loadbalancer::ReserveLoadBalancerReply* resp) {
               return service->ReserveLoadBalancer(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LoadBalancer_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LoadBalancer::Service, ::loadbalancer::GetLoadBalancerRequest, ::loadbalancer::ReserveLoadBalancerReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LoadBalancer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::loadbalancer::GetLoadBalancerRequest* req,
             ::loadbalancer::ReserveLoadBalancerReply* resp) {
               return service->GetLoadBalancer(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LoadBalancer_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LoadBalancer::Service, ::loadbalancer::LoadBalancerStatusRequest, ::loadbalancer::LoadBalancerStatusReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LoadBalancer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::loadbalancer::LoadBalancerStatusRequest* req,
             ::loadbalancer::LoadBalancerStatusReply* resp) {
               return service->LoadBalancerStatus(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LoadBalancer_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LoadBalancer::Service, ::loadbalancer::FreeLoadBalancerRequest, ::loadbalancer::FreeLoadBalancerReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LoadBalancer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::loadbalancer::FreeLoadBalancerRequest* req,
             ::loadbalancer::FreeLoadBalancerReply* resp) {
               return service->FreeLoadBalancer(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LoadBalancer_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LoadBalancer::Service, ::loadbalancer::AddSendersRequest, ::loadbalancer::AddSendersReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LoadBalancer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::loadbalancer::AddSendersRequest* req,
             ::loadbalancer::AddSendersReply* resp) {
               return service->AddSenders(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LoadBalancer_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LoadBalancer::Service, ::loadbalancer::RemoveSendersRequest, ::loadbalancer::RemoveSendersReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LoadBalancer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::loadbalancer::RemoveSendersRequest* req,
             ::loadbalancer::RemoveSendersReply* resp) {
               return service->RemoveSenders(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LoadBalancer_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LoadBalancer::Service, ::loadbalancer::RegisterRequest, ::loadbalancer::RegisterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LoadBalancer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::loadbalancer::RegisterRequest* req,
             ::loadbalancer::RegisterReply* resp) {
               return service->Register(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LoadBalancer_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LoadBalancer::Service, ::loadbalancer::SetSlotDemandsRequest, ::loadbalancer::SetSlotDemandsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LoadBalancer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::loadbalancer::SetSlotDemandsRequest* req,
             ::loadbalancer::SetSlotDemandsReply* resp) {
               return service->SetSlotDemands(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LoadBalancer_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LoadBalancer::Service, ::loadbalancer::DeregisterRequest, ::loadbalancer::DeregisterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LoadBalancer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::loadbalancer::DeregisterRequest* req,
             ::loadbalancer::DeregisterReply* resp) {
               return service->Deregister(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LoadBalancer_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LoadBalancer::Service, ::loadbalancer::SendStateRequest, ::loadbalancer::SendStateReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LoadBalancer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::loadbalancer::SendStateRequest* req,
             ::loadbalancer::SendStateReply* resp) {
               return service->SendState(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LoadBalancer_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LoadBalancer::Service, ::loadbalancer::OverviewRequest, ::loadbalancer::OverviewReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LoadBalancer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::loadbalancer::OverviewRequest* req,
             ::loadbalancer::OverviewReply* resp) {
               return service->Overview(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LoadBalancer_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LoadBalancer::Service, ::loadbalancer::TimeseriesRequest, ::loadbalancer::TimeseriesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LoadBalancer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::loadbalancer::TimeseriesRequest* req,
             ::loadbalancer::TimeseriesResponse* resp) {
               return service->Timeseries(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LoadBalancer_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LoadBalancer::Service, ::loadbalancer::VersionRequest, ::loadbalancer::VersionReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LoadBalancer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::loadbalancer::VersionRequest* req,
             ::loadbalancer::VersionReply* resp) {
               return service->Version(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LoadBalancer_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LoadBalancer::Service, ::loadbalancer::CreateTokenRequest, ::loadbalancer::CreateTokenReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LoadBalancer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::loadbalancer::CreateTokenRequest* req,
             ::loadbalancer::CreateTokenReply* resp) {
               return service->CreateToken(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LoadBalancer_method_names[14],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LoadBalancer::Service, ::loadbalancer::ListTokenPermissionsRequest, ::loadbalancer::ListTokenPermissionsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LoadBalancer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::loadbalancer::ListTokenPermissionsRequest* req,
             ::loadbalancer::ListTokenPermissionsReply* resp) {
               return service->ListTokenPermissions(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LoadBalancer_method_names[15],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LoadBalancer::Service, ::loadbalancer::ListChildTokensRequest, ::loadbalancer::ListChildTokensReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LoadBalancer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::loadbalancer::ListChildTokensRequest* req,
             ::loadbalancer::ListChildTokensReply* resp) {
               return service->ListChildTokens(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LoadBalancer_method_names[16],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LoadBalancer::Service, ::loadbalancer::RevokeTokenRequest, ::loadbalancer::RevokeTokenReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LoadBalancer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::loadbalancer::RevokeTokenRequest* req,
             ::loadbalancer::RevokeTokenReply* resp) {
               return service->RevokeToken(ctx, req, resp);
             }, this)));
}

LoadBalancer::Service::~Service() {
}

::grpc::Status LoadBalancer::Service::ReserveLoadBalancer(::grpc::ServerContext* context, const ::loadbalancer::ReserveLoadBalancerRequest* request, ::loadbalancer::ReserveLoadBalancerReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LoadBalancer::Service::GetLoadBalancer(::grpc::ServerContext* context, const ::loadbalancer::GetLoadBalancerRequest* request, ::loadbalancer::ReserveLoadBalancerReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LoadBalancer::Service::LoadBalancerStatus(::grpc::ServerContext* context, const ::loadbalancer::LoadBalancerStatusRequest* request, ::loadbalancer::LoadBalancerStatusReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LoadBalancer::Service::FreeLoadBalancer(::grpc::ServerContext* context, const ::loadbalancer::FreeLoadBalancerRequest* request, ::loadbalancer::FreeLoadBalancerReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LoadBalancer::Service::AddSenders(::grpc::ServerContext* context, const ::loadbalancer::AddSendersRequest* request, ::loadbalancer::AddSendersReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LoadBalancer::Service::RemoveSenders(::grpc::ServerContext* context, const ::loadbalancer::RemoveSendersRequest* request, ::loadbalancer::RemoveSendersReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LoadBalancer::Service::Register(::grpc::ServerContext* context, const ::loadbalancer::RegisterRequest* request, ::loadbalancer::RegisterReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LoadBalancer::Service::SetSlotDemands(::grpc::ServerContext* context, const ::loadbalancer::SetSlotDemandsRequest* request, ::loadbalancer::SetSlotDemandsReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LoadBalancer::Service::Deregister(::grpc::ServerContext* context, const ::loadbalancer::DeregisterRequest* request, ::loadbalancer::DeregisterReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LoadBalancer::Service::SendState(::grpc::ServerContext* context, const ::loadbalancer::SendStateRequest* request, ::loadbalancer::SendStateReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LoadBalancer::Service::Overview(::grpc::ServerContext* context, const ::loadbalancer::OverviewRequest* request, ::loadbalancer::OverviewReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LoadBalancer::Service::Timeseries(::grpc::ServerContext* context, const ::loadbalancer::TimeseriesRequest* request, ::loadbalancer::TimeseriesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LoadBalancer::Service::Version(::grpc::ServerContext* context, const ::loadbalancer::VersionRequest* request, ::loadbalancer::VersionReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LoadBalancer::Service::CreateToken(::grpc::ServerContext* context, const ::loadbalancer::CreateTokenRequest* request, ::loadbalancer::CreateTokenReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LoadBalancer::Service::ListTokenPermissions(::grpc::ServerContext* context, const ::loadbalancer::ListTokenPermissionsRequest* request, ::loadbalancer::ListTokenPermissionsReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LoadBalancer::Service::ListChildTokens(::grpc::ServerContext* context, const ::loadbalancer::ListChildTokensRequest* request, ::loadbalancer::ListChildTokensReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LoadBalancer::Service::RevokeToken(::grpc::ServerContext* context, const ::loadbalancer::RevokeTokenRequest* request, ::loadbalancer::RevokeTokenReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace loadbalancer
#include <grpcpp/ports_undef.inc>

